feat: simplify block to only be data and cid
ipfs/js-ipfs-block pull request #31
Opened 2017-03-15 21:08 UTC by dignifiedquire

Ref https://github.com/ipfs/js-ipfs-repo/pull/123

2017-03-15 21:08 UTC, dignifiedquire commented
refhttps://github.com/ipfs/js-ipfs/issues/787

2017-03-17 00:22 UTC, diasdavid commented
@dignifiedquire do I need to say it again? no yarn.lock :(

2017-03-17 12:43 UTC, daviddias requested changes
- [x] remove yarn.lock
- [x] update to aegir 11 (I'm being fair 😇)

2017-03-17 12:43 UTC, diasdavid commented on src/index.js
> +  static isBlock (other) {
Still making my mind over this, but currently, I strongly feel that public module methods shouldn't be encapsulated in Class objects and made public with `static`.

I've seen a lot of cases of people starting to use `static` and then forgetting what it really means and start mutating the state.

Plus, it is way more understandable from a Node.js/CJS user if the "module.exports" is the only place that tells me what gets exported.

2017-03-17 12:43 UTC, diasdavid commented on src/index.js
> +      throw new Error('data must be a buffer')
first argument must be a Buffer

2017-03-17 12:43 UTC, diasdavid commented on src/index.js
> +      throw new Error('cid must be a CID')
second argument must be a CID

2017-03-17 14:35 UTC, dignifiedquire commented on src/index.js
> +  static isBlock (other) {
Declaring `Block.isBlock = ...` doesn't seem to be any better to me in terms of understanding.

2017-03-17 14:36 UTC, dignifiedquire commented on src/index.js
> +  static isBlock (other) {
also we started using this a while ago in modules like cid

2017-03-17 14:49 UTC, diasdavid commented on src/index.js
> +  static isBlock (other) {
where? https://github.com/ipld/js-cid/blob/master/src/index.js#L133-L135

2017-03-17 16:22 UTC, dignifiedquire commented on src/index.js
> +  static isBlock (other) {
fine

2017-03-17 16:25 UTC, dignifiedquire commented on src/index.js
> +  static isBlock (other) {
one bonus is that jsdoc picks up the right docs for this if we write it as static

2017-03-17 16:28 UTC, dignifiedquire commented
applied all cr except the static thing

2017-03-20 22:08 UTC, daviddias commented on src/index.js
> +  static isBlock (other) {
hm.....

2017-03-20 22:09 UTC, merged