fix: transition to async crypto api
ipfs/js-ipfs-block pull request #4
Opened 2016-09-26 20:16 UTC by dignifiedquire

BREAKING CHANGE:
Constructor requires a hash now and there is now Block.create(data, type, cb)

2016-10-05 14:36 UTC, daviddias requested changes

2016-10-05 14:36 UTC, diasdavid commented on README.md
> +#### `Block.create(data, key, [type, ] callback)`
Let's just go ahead and take from https://github.com/ipfs/js-ipfs-block/pull/5 the fact that .key becomes a function and make it an async function.

2016-10-05 14:36 UTC, diasdavid commented on package.json
>      "aegir": "^8.0.0",
update to latest

2016-10-05 15:30 UTC, dignifiedquire commented on README.md
> +#### `Block.create(data, key, [type, ] callback)`
@diasdavid done, please review the new api before I start propagating

2016-10-12 13:38 UTC, daviddias commented on package.json
>      "aegir": "^8.0.0",
🛎

2016-10-12 13:39 UTC, diasdavid commented
API looks good, needs a test that tests with a different hash func

2016-10-31 10:49 UTC, daviddias requested changes
Overall LGTM

2016-10-31 10:49 UTC, diasdavid commented on README.md
> +    - [`block.key([hashFn,] callback)`](#blockkeyhashfn-callback)
`s/hashFn/hashAlg`

2016-10-31 10:49 UTC, diasdavid commented on README.md
> +#### `block.key([hashFn,] callback)`
`s/hashFn/hashAlg`

2016-10-31 11:01 UTC, daviddias approved these changes

2016-11-03 11:31 UTC, diasdavid commented on src/index.js
> +  })
👍

2016-11-03 11:54 UTC, Kubuxu commented on src/index.js
> +      setImmediate(() => {
`setImmediate` isn't supported by FF or Chrome, will it be a problem?

2016-11-03 11:59 UTC, dignifiedquire commented on src/index.js
> +      setImmediate(() => {
hmm thanks for pointing this out, need to find a better solution :(

2016-11-03 12:02 UTC, Kubuxu commented on src/index.js
> +      setImmediate(() => {
`setImmediate` is also used in 4 different places across the codebase. There is also polyfill for it if it comes to it.

2016-11-03 12:04 UTC, dignifiedquire commented on src/index.js
> +      setImmediate(() => {
yeah we were shipping one before, but not anymore. As we already use `async` I'm going to use `async.setImmediate` http://caolan.github.io/async/docs.html#setImmediate

2016-11-03 12:06 UTC, dignifiedquire commented on src/index.js
> +      setImmediate(() => {
fixed

2016-11-03 12:40 UTC, merged